### ISSUE TITLE
Página de gravações

### ISSUE THREAD

**Issue by iagoscm** [Requisitos-de-Software/2022.2-CNH#4]
- [ ] Criar a página de gravações e subir a primeira gravação, definindo também que é a segunda reunião que fazemos;
- [ ] Histórico de versões.

**Comment by luciano-freitas-melo** [comment]
Acho que as gravações podem ser só links junto das atas de reunião, ao invés de uma página só para as gravações. O que acham?

**Comment by iagoscm** [comment]
verdade, bem melhor

**Comment by iagoscm** [comment]
Decidimos que as gravações serão juntas das atas, então
TCHAU, QUERIDA.
